// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwkriyjknveiyzinydzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3a3JpeWprbnZlaXl6aW55ZHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzAzMjIsImV4cCI6MjA2OTkwNjMyMn0.Dvn_5OFw7m5rzqdKTlGWnhqyBvWwv6Vq9r55oYZ73MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});